'use strict';
let state, page='overview', busy=false, idle=Date.now();
const requestKeys=new Map();
function newRequestId(){const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;return [...bytes].map(x=>x.toString(16).padStart(2,'0')).join('');}
function keyed(kind,data){const sig=kind+JSON.stringify(data);if(!requestKeys.has(sig))requestKeys.set(sig,newRequestId());return {...data,request_id:requestKeys.get(sig)};}
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stamp=x=>x?new Date(x).toLocaleString():'';
async function api(path,data){
  const r=await fetch(path,{credentials:'same-origin',headers:data?{'Content-Type':'application/json'}:{},method:data?'POST':'GET',body:data?JSON.stringify(data):undefined});
  const out=await r.json(); if(!r.ok){if(r.status===401)showLogin();throw Error(out.error||'Request failed');}return out;
}
function showLogin(){$('login-view').hidden=false;$('app').hidden=true;state=null;$('detail').close();}
async function run(fn){if(busy)return;busy=true;$('app-error').textContent='';try{await fn();}catch(e){$('app-error').textContent=e.message;const err=$('detail-content').querySelector('.error');if(err)err.textContent=e.message;}finally{busy=false;}}
async function refresh(){state=await api('/v2/state');if(state.user.role!=='admin'){await api('/logout',{});throw Error('Use the Android app for your staff account.');}$('login-view').hidden=true;$('app').hidden=false;$('account-name').textContent=state.user.username;$('demo-banner').hidden=state.mode!=='demo';$('last-updated').textContent='Updated '+new Date().toLocaleTimeString();render();}
function table(rows,cols){return '<div class="table-wrap"><table><thead><tr>'+cols.map(c=>'<th>'+esc(c[0])+'</th>').join('')+'</tr></thead><tbody>'+(rows.length?rows.map(r=>'<tr>'+cols.map(c=>'<td>'+(typeof c[1]==='function'?c[1](r):esc(r[c[1]]))+'</td>').join('')+'</tr>').join(''):'<tr><td colspan="'+cols.length+'">No records yet.</td></tr>')+'</tbody></table></div>';}
const btn=(label,attr)=>'<button class="secondary" '+attr+'>'+esc(label)+'</button>';
function panel(title,html){return '<article class="panel"><div class="panel-head"><h2>'+esc(title)+'</h2></div>'+html+'</article>';}
const product=id=>state.products.find(p=>p.id===id)?.name||id;
const productTable=()=>table(state.products,[['Rice product','name'],['SKU','sku'],['Sack size',()=> '25 kg'],['Available sacks','quantity'],['Stock version','version'],['',p=>btn('Edit details','data-product="'+p.id+'"')]]);
const historyTable=rows=>table(rows,[['Time',r=>esc(stamp(r.created_at))],['Rice product','name'],['Action','kind'],['Previous','previous_quantity'],['Change','difference'],['New stock','quantity'],['Account','username'],['Reason','reason']]);
function render(){
  if(!state)return;
  document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));
  const titles={overview:'Overview',inventory:'Rice products',actions:'Scans and counts',cases:'Returns and damage',history:'Stock movement history',accounts:'Accounts and permissions',reports:'Reports and exports',security:'Account security'};$('page-title').textContent=titles[page];
  const descriptions={overview:'Your warehouse, at a glance.',inventory:'Manage the rice products in your warehouse.',actions:'Review scans, count comparisons, and stock corrections.',cases:'Inspect returned or damaged sacks and record your decision.',history:'Every stock movement, with its account and reason.',accounts:'Manage staff access and account permissions.',reports:'Download your complete warehouse records.',security:'Keep your administrator account secure.'};$('page-description').textContent=descriptions[page];
  let html='';
  if(page==='overview'){
    const metrics=[['Available sacks',state.products.reduce((n,p)=>n+p.quantity,0),'Across all rice products · 25 kg each'],['Awaiting inspection',state.cases.filter(c=>c.remaining>0).length,'Owner decision required'],['Open actions',state.actions.filter(a=>a.state==='open').length,'Scans have not changed stock']];
    html='<div class="metrics">'+metrics.map(m=>'<article><p>'+esc(m[0])+'</p><strong>'+m[1]+'</strong><span>'+esc(m[2])+'</span></article>').join('')+'</div>'+panel('Available stock',productTable())+panel('Recent stock movements',historyTable(state.history.slice(0,8)));
  }
  if(page==='inventory')html=panel('Selected rice products','<p class="muted">Each sack counts as one unit. Stock changes through verified transactions and complete-count corrections.</p><label>Search rice product or SKU<input id="search" type="search"></label><div id="product-table">'+productTable()+'</div>');
  if(page==='actions')html=panel('Staff actions',table(state.actions,[['Time',r=>esc(stamp(r.created_at))],['Staff','username'],['Transaction','kind'],['Status',r=>'<span class="badge">'+esc(r.state)+'</span>'],['',r=>btn('Review','data-action="'+esc(r.id)+'"')]]));
  if(page==='cases')html=panel('Returns and damaged sacks','<p class="muted">Pending records leave stock unchanged. Inspect the sacks before approving usable restocking, repacking, or unusable disposal.</p>'+table(state.cases,[['Time',r=>esc(stamp(r.created_at))],['Rice','name'],['Record','kind'],['Quantity','quantity'],['Undecided','remaining'],['Already in stock',r=>r.already_stocked?'Yes':'No'],['Condition','condition'],['Status','status'],['Staff','username'],['Evidence',r=>btn('View images','data-action="'+esc(r.action_id)+'"')],['',r=>r.remaining?btn('Inspect and decide','data-case="'+esc(r.id)+'"'):'Resolved']]))+panel('Owner decision history',table(state.decisions||[],[['Time',r=>esc(stamp(r.created_at))],['Decision','decision'],['Sacks','quantity'],['Stock change','difference'],['Approver','username'],['Reason','reason']]));
  if(page==='history')html=panel('Stock-in, stock-out and corrections',btn('Export CSV','id="export"')+historyTable(state.history));
  if(page==='reports')html=panel('Download complete records','<p class="muted">These exports include all saved records. The stock history screen shows the latest 1,000 movements.</p><label>Report<select id="report-kind"><option value="inventory">Rice stock balances</option><option value="history">Stock-in, stock-out and adjustments</option><option value="counts">Count comparisons and corrections</option><option value="cases">Returns and damage</option><option value="decisions">Owner decision history</option><option value="scans">Original and checked scan results</option></select></label>'+btn('Download CSV','id="download-report"')+btn('Download JSON','id="download-json"'));
  if(page==='accounts')html=panel('Account permissions',table(state.users,[['Account','username'],['Role',r=>r.role==='operator'?'Warehouse staff':esc(r.role)],['Active',r=>r.active?'Yes':'No'],['Adjust counts',r=>r.role==='admin'||r.can_adjust?'Allowed':'Not allowed'],['',r=>btn('Manage access','data-user="'+r.id+'"')]]))+panel('Create account','<form id="new-user"><label>Username<input name="username" required></label><label>Password<input name="password" type="password" minlength="12" maxlength="128" required></label><label>Role<select name="role"><option value="operator">Warehouse staff</option><option value="admin">Administrator / owner</option><option value="viewer">Read only</option></select></label><button class="primary">Create account</button></form>');
  if(page==='security')html=panel('Change your password','<form id="security"><label>Current password<input name="current_password" type="password" required></label><label>New password<input name="new_password" type="password" minlength="12" maxlength="128" required></label><label>Confirm new password<input name="confirm" type="password" required></label><p class="muted">Changing your password signs out all devices using this account.</p><button class="primary">Change password</button></form>');
  $('content').innerHTML=html;
  $('search')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();$('product-table').innerHTML=table(state.products.filter(p=>(p.name+p.sku).toLowerCase().includes(q)),[['Rice','name'],['SKU','sku'],['Available sacks','quantity'],['',p=>btn('Edit details','data-product="'+p.id+'"')]]);});
  $('new-user')?.addEventListener('submit',e=>{e.preventDefault();run(async()=>{await api('/users',Object.fromEntries(new FormData(e.target)));await refresh();});});
  $('security')?.addEventListener('submit',e=>{e.preventDefault();run(async()=>{const d=Object.fromEntries(new FormData(e.target));if(d.new_password!==d.confirm)throw Error('Passwords do not match');delete d.confirm;await api('/account/security',{...d,action:'change_password'});showLogin();});});
  $('export')?.addEventListener('click',()=>run(()=>downloadReport('history','csv')));
  $('download-report')?.addEventListener('click',()=>run(()=>downloadReport($('report-kind').value,'csv')));
  $('download-json')?.addEventListener('click',()=>run(()=>downloadReport($('report-kind').value,'json')));
}
async function downloadReport(kind,format){
  const {rows}=await api('/v2/report?kind='+encodeURIComponent(kind));
  let content=JSON.stringify(rows,null,2);
  if(format==='csv'){const keys=rows.length?Object.keys(rows[0]):[];content=[keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');}
  const url=URL.createObjectURL(new Blob([content],{type:format==='csv'?'text/csv':'application/json'}));const a=document.createElement('a');a.href=url;a.download='MOVIS-'+kind+'.'+format;a.click();URL.revokeObjectURL(url);
}
function dialog(title,html){$('detail-content').innerHTML='<h2>'+esc(title)+'</h2>'+html+'<p class="error" role="alert"></p>';$('detail').showModal();}
$('content').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;run(async()=>{
  if(b.dataset.action){const r=await api('/v2/state?action_id='+encodeURIComponent(b.dataset.action)+'&images=1'),a=r.action;
    let html='<p>'+esc(a.kind)+'  |  '+esc(a.state)+'  |  '+esc(a.created_at)+'</p>';
    html+=table(a.comparison,[['Rice',x=>esc(product(x.product_id))],['Recorded','quantity'],['Full count','count'],['Difference','difference'],['Correction',x=>x.adjusted?'Applied':'Not applied']]);
    const pending=a.comparison.filter(c=>c.difference&&!c.adjusted);
    if(a.state==='finished'&&pending.length)html+='<form id="adjust"><p>Select products to correct:</p>'+pending.map(c=>'<label><input type="checkbox" name="product" value="'+c.product_id+'" checked> '+esc(product(c.product_id))+'  ->  '+c.count+' sacks</label>').join('')+'<label>Reason<input name="reason" required></label><button class="primary">Confirm adjustment</button></form>';
    for(const im of a.images){html+='<article class="panel"><h3>'+(im.deleted?'Deleted image':'Captured image')+'</h3>'+(im.image?'<a href="data:image/jpeg;base64,'+esc(im.image)+'" target="_blank"><img alt="Captured rice sacks" src="data:image/jpeg;base64,'+esc(im.image)+'"></a>':'')+'<p>'+esc(im.model_version)+'  |  '+esc(im.processing_ms)+' ms  |  '+(im.reviewed?'Checked':'Unchecked')+'</p>'+table(im.raw,[['Raw rice','name'],['Confidence',x=>esc(Math.round(x.confidence*100)+'%')],['Box',x=>esc(JSON.stringify(x.box))]])+table(im.checked,[['User checked rice',x=>esc(product(x.product_id))],['Sacks','quantity']])+'</article>';}
    dialog('Review action and scan evidence',html);
    $('adjust')?.addEventListener('submit',ev=>{ev.preventDefault();run(async()=>{const f=new FormData(ev.target);await api('/v2/adjust',keyed('adjust',{action_id:a.id,revision:a.revision,products:f.getAll('product').map(Number),reason:f.get('reason'),confirmed:true}));$('detail').close();await refresh();});});
  }
  if(b.dataset.case){const c=state.cases.find(c=>c.id===b.dataset.case);dialog('Owner inspection: '+c.name,'<p>'+esc(c.reason)+'  |  '+esc(c.condition)+'</p><p>'+c.remaining+' sacks await a decision. '+(c.already_stocked?'Already included in stock.':'Not yet included in stock.')+'</p><form id="decision"><label>Decision<select name="decision"><option value="restock">Return usable sacks to stock</option><option value="repack">Repack usable sacks and approve stock disposition</option><option value="dispose">Dispose of unusable sacks</option></select></label><label>Sacks<input name="quantity" type="number" min="1" max="'+c.remaining+'" value="'+c.remaining+'" required></label><label>Inspection and decision reason<input name="reason" required></label><label><input name="inspected" type="checkbox" required> I inspected the rice and packaging</label><label><input name="usable" type="checkbox"> Rice is usable</label><label><input name="unusable" type="checkbox"> Rice is unusable</label><p id="stock-effect" class="muted"></p><button class="primary">Approve decision</button></form>');const effect=()=>{const form=$('decision'),q=Number(form.elements.quantity.value),kind=form.elements.decision.value;const delta=kind==='dispose'?(c.already_stocked?-q:0):(c.already_stocked?0:q);$('stock-effect').textContent='Approved stock change: '+(delta>0?'+':'')+delta+' sacks. '+(kind==='repack'&&!c.already_stocked?'Approval includes returning the usable repacked sacks to stock.':'');};$('decision').addEventListener('input',effect);effect();$('decision').onsubmit=ev=>{ev.preventDefault();const f=new FormData(ev.target),d={case_id:c.id,request_id:newRequestId(),quantity:Number(f.get('quantity')),decision:f.get('decision'),reason:f.get('reason'),inspected:f.has('inspected'),usable:f.has('usable'),unusable:f.has('unusable')};ev.target.dataset.request=ev.target.dataset.request||JSON.stringify(d);run(async()=>{const stored=JSON.parse(ev.target.dataset.request);if(JSON.stringify({...stored,request_id:d.request_id})!==JSON.stringify(d))ev.target.dataset.request=JSON.stringify(d);await api('/v2/decision',JSON.parse(ev.target.dataset.request));$('detail').close();await refresh();});};}
  if(b.dataset.user){const u=state.users.find(u=>u.id===Number(b.dataset.user));dialog('Access for '+u.username,'<form id="access"><label><input type="checkbox" name="active" '+(u.active?'checked':'')+'> Account active</label><label><input type="checkbox" name="can_adjust" '+(u.can_adjust?'checked':'')+'> Allow full-count stock corrections</label><p>Administrators carry owner approval authority. Staff cannot approve returns or damage decisions.</p><button class="primary">Save permissions</button></form>');$('access').onsubmit=ev=>{ev.preventDefault();const f=new FormData(ev.target);run(async()=>{await api('/v2/users',{user_id:u.id,active:f.has('active'),can_adjust:f.has('can_adjust')});$('detail').close();await refresh();});};}
  if(b.dataset.product){const p=state.products.find(p=>p.id===Number(b.dataset.product));dialog(p.name,'<form id="product"><label>SKU<input name="sku" value="'+esc(p.sku)+'" required></label><label>Description<input name="description" value="'+esc(p.description)+'" required></label><label>YOLO class label<input name="model_class" value="'+esc(p.model_class)+'" required></label><button class="primary">Save details</button></form>');$('product').onsubmit=ev=>{ev.preventDefault();run(async()=>{await api('/v2/product',{...Object.fromEntries(new FormData(ev.target)),product_id:p.id});$('detail').close();await refresh();});};}
});});
$('close-detail').onclick=()=>$('detail').close();
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();});
$('refresh').onclick=()=>run(refresh);
$('logout').onclick=()=>run(async()=>{await api('/logout',{});showLogin();});
$('login-form').onsubmit=async e=>{e.preventDefault();const submit=e.target.querySelector('button[type=submit]');if(submit.disabled)return;submit.disabled=true;submit.textContent='Signing in…';$('login-error').textContent='';try{await api('/login',{username:$('username').value.trim(),password:$('password').value,client:'web'});$('password').value='';await refresh();}catch(e){$('login-error').textContent=e.message;}finally{submit.disabled=false;submit.innerHTML='Sign in <span aria-hidden="true">→</span>';}};
for(const evt of ['pointerdown','keydown'])document.addEventListener(evt,()=>idle=Date.now());
setInterval(()=>{if(!state||busy)return;if(Date.now()-idle>15*60*1000){run(async()=>{await api('/logout',{});showLogin();});return;}if(!$('detail').open&&['overview','history'].includes(page))run(refresh);},15000);
run(async()=>{try{await refresh();}catch(e){if(e.message!=='Please sign in again')$('login-error').textContent=e.message;}});
